### ISSUE TITLE
Question about the extension button.

### ISSUE THREAD

**Issue by dmitshur** [yifanwu/blanknewtab#1]
Hi @yifanwu,

I think Chrome (stable channel) has made some change in one of the recent updates where all extensions will display a button. Previously, right clicking the button and hiding it would actually hide it from view. But now it appears in the menu bar:

![image](https://cloud.githubusercontent.com/assets/1924134/14197210/b6283744-f780-11e5-80f9-420daae41148.png)

I am wondering where that text is coming from. The "That's the tool tip" string. I don't see it anywhere in the source, is it coming from Chrome somehow? Or is the source of the published extension (i.e., https://chrome.google.com/webstore/detail/blank-new-tab/beafekehjfhnkpnnjegadfdncaipnljp) slightly different than what's in this repo?

Thanks!

**Comment by dmitshur** [comment]
> Or is the source of the published extension (i.e., https://chrome.google.com/webstore/detail/blank-new-tab/beafekehjfhnkpnnjegadfdncaipnljp) slightly different than what's in this repo?

The extension in Chrome Web Store is at version 0.0.2, while the `manifest.json` file in this repository is at version 0.0.1:

https://github.com/yifanwu/blanknewtab/blob/1bcdc65398634ecd8799849886c41b50cc59b92a/manifest.json#L3

So that must mean the source code here is slightly out of date. That would explain the difference I was seeing.

Closing since this question has been answered.

**Comment by yifanwu** [comment]
Hey @dmitshur sorry I just saw this question now; seems like it's fixed? Otherwise I'm happy to review a PR : )

**Comment by dmitshur** [comment]
No worries! I inferred the answer from public information that I could find. :)
